"""Corpus composition reconnaissance (no indexing, no retrieval).

Priority:
1) Try `cloc --by-file --csv` when available.
2) Fallback to built-in lightweight line counter.

Intranet placeholder flow (do not run on this machine):
1) python scripts/00_sync_and_pin.py --vcs svn --svn-url <SVN_URL>
2) python scripts/corpus_recon.py --root "D:\\wirebonder_export\\corpus\\r12345" --corpus-tag r12345
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
import subprocess
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROOT = LAB_ROOT / "repos" / "Smoothieware"
DEFAULT_NOTES = LAB_ROOT / "notes" / "wirebonder_corpus_recon.md"
DEFAULT_BY_FILE = LAB_ROOT / "logs" / "corpus_recon_by_file.csv"
DEFAULT_SUMMARY = LAB_ROOT / "logs" / "corpus_recon_summary.json"

CODE_EXTS = {
    ".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx",
    ".rc", ".idl", ".inl", ".def", ".asm", ".s",
}
COMMENT_PREFIX = ("//",)
BLOCK_OPEN = "/*"
BLOCK_CLOSE = "*/"

VENDORED_TOKENS = {
    "third_party", "thirdparty", "vendor", "external", "extern",
    "deps", "dependency", "dependencies",
    "mbed",
}
LIB_TOKENS = {"lib", "libs", "library", "libraries"}
LICENSE_NAMES = {
    "license", "license.txt", "license.md", "copying", "copying.txt",
    "notice", "notice.txt",
}
README_NAMES = {"readme", "readme.md", "readme.txt", "readme.rst"}
GENERATED_EXTS = {".rc"}
GENERATED_MARKERS = (
    "generated", "auto-generated", "autogenerated", "do not edit",
    "classwizard", "mfc classwizard", "resource script generated",
)
COPYRIGHT_RE = re.compile(r"(copyright[^\\n\\r]*)", re.IGNORECASE)


@dataclass
class FileStat:
    path: str
    ext: str
    code: int
    comment: int
    blank: int
    language: str
    generated: bool
    vendored: bool

    @property
    def total(self) -> int:
        return self.code + self.comment + self.blank


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def lang_from_ext(ext: str) -> str:
    m = {
        ".c": "C/C++ Header",
        ".cc": "C++",
        ".cpp": "C++",
        ".cxx": "C++",
        ".h": "C/C++ Header",
        ".hh": "C/C++ Header",
        ".hpp": "C/C++ Header",
        ".hxx": "C/C++ Header",
        ".rc": "Resource",
        ".idl": "IDL",
        ".inl": "Inline",
        ".def": "Def",
        ".asm": "Asm",
        ".s": "Asm",
    }
    return m.get(ext.lower(), "Text")


def parse_with_cloc(root: Path) -> list[FileStat] | None:
    if not shutil.which("cloc"):
        return None
    cmd = [
        "cloc",
        str(root),
        "--by-file",
        "--csv",
        "--quiet",
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except (subprocess.SubprocessError, OSError):
        return None
    rows = []
    for row in csv.DictReader(proc.stdout.splitlines()):
        filename = (row.get("filename") or "").strip()
        if not filename:
            continue
        p = Path(filename)
        ext = p.suffix.lower()
        if ext not in CODE_EXTS:
            continue
        rows.append(
            FileStat(
                path=str(Path(filename).resolve().relative_to(root.resolve())).replace("\\", "/"),
                ext=ext,
                code=int(row.get("code", 0) or 0),
                comment=int(row.get("comment", 0) or 0),
                blank=int(row.get("blank", 0) or 0),
                language=(row.get("language") or lang_from_ext(ext)),
                generated=False,
                vendored=False,
            )
        )
    return rows


def parse_builtin(root: Path) -> list[FileStat]:
    out: list[FileStat] = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        ext = p.suffix.lower()
        if ext not in CODE_EXTS:
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        code = 0
        comment = 0
        blank = 0
        in_block = False
        for line in text.splitlines():
            original = line
            i = 0
            n = len(original)
            has_comment = False
            has_code = False
            in_string: str | None = None

            while i < n:
                ch = original[i]
                nxt = original[i + 1] if i + 1 < n else ""

                if in_block:
                    has_comment = True
                    if ch == "*" and nxt == "/":
                        in_block = False
                        i += 2
                        continue
                    i += 1
                    continue

                if in_string is not None:
                    if ch == "\\":
                        i += 2
                        continue
                    if ch == in_string:
                        in_string = None
                    has_code = True
                    i += 1
                    continue

                if ch in ("'", "\""):
                    in_string = ch
                    has_code = True
                    i += 1
                    continue

                if ch == "/" and nxt == "/":
                    has_comment = True
                    break
                if ch == "/" and nxt == "*":
                    has_comment = True
                    in_block = True
                    i += 2
                    continue
                if not ch.isspace():
                    has_code = True
                i += 1

            if has_code:
                code += 1
            elif has_comment:
                comment += 1
            else:
                blank += 1
        out.append(
            FileStat(
                path=str(p.resolve().relative_to(root.resolve())).replace("\\", "/"),
                ext=ext,
                code=code,
                comment=comment,
                blank=blank,
                language=lang_from_ext(ext),
                generated=False,
                vendored=False,
            )
        )
    return out


def has_license_file(d: Path) -> bool:
    try:
        for c in d.iterdir():
            if c.is_file() and c.name.lower() in LICENSE_NAMES:
                return True
    except OSError:
        return False
    return False


def has_readme_file(d: Path) -> bool:
    try:
        for c in d.iterdir():
            if c.is_file() and c.name.lower() in README_NAMES:
                return True
    except OSError:
        return False
    return False


def sample_copyright_signatures(root: Path, prefix: str, stats: list[FileStat], limit: int = 20) -> set[str]:
    sigs: set[str] = set()
    matched = [s for s in stats if s.path.startswith(prefix + "/") or s.path == prefix]
    for st in matched[:limit]:
        p = root / st.path
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        head = "\n".join(text.splitlines()[:80])
        for m in COPYRIGHT_RE.findall(head):
            sigs.add(m.strip().lower())
    return sigs


def vendored_candidates(root: Path, stats: list[FileStat]) -> dict[str, int]:
    by_dir = defaultdict(int)
    for st in stats:
        p = Path(st.path)
        for i in range(1, min(5, len(p.parts)) + 1):
            d = Path(*p.parts[:i])
            by_dir[str(d).replace("\\", "/")] += st.total

    candidates: dict[str, int] = {}
    for rel, lines in by_dir.items():
        parts = rel.lower().split("/")
        if any(tok in parts for tok in VENDORED_TOKENS):
            candidates[rel] = lines
            continue
        if any(tok in parts for tok in LIB_TOKENS):
            abs_dir = root / rel
            if has_license_file(abs_dir):
                candidates[rel] = lines

    # Heuristic A: top-level sibling tree with own LICENSE/README and substantial size.
    top_level_lines: dict[str, int] = defaultdict(int)
    for st in stats:
        p = Path(st.path)
        if p.parts:
            top_level_lines[p.parts[0]] += st.total
    total = sum(top_level_lines.values()) or 1
    src_sigs = sample_copyright_signatures(root, "src", stats)
    for top, lines in top_level_lines.items():
        if top == "src":
            continue
        top_abs = root / top
        ratio = lines / total
        if ratio < 0.05:  # focus on big trees; over-reporting small dirs not useful here
            continue
        if has_license_file(top_abs) or has_readme_file(top_abs):
            candidates[top] = max(candidates.get(top, 0), lines)
            continue
        # Heuristic B: copyright header signature clearly differs from src tree.
        top_sigs = sample_copyright_signatures(root, top, stats)
        if top_sigs and (not src_sigs or top_sigs.isdisjoint(src_sigs)):
            candidates[top] = max(candidates.get(top, 0), lines)
    return dict(sorted(candidates.items(), key=lambda kv: -kv[1]))


def generated_file(path: Path) -> bool:
    if path.suffix.lower() in GENERATED_EXTS:
        return True
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()[:40]
    except OSError:
        return False
    head = "\n".join(lines).lower()
    return any(m in head for m in GENERATED_MARKERS)


def mark_flags(root: Path, stats: list[FileStat]) -> None:
    vendored_dirs = vendored_candidates(root, stats)
    vendored_keys = list(vendored_dirs.keys())
    for st in stats:
        sp = st.path.lower()
        st.vendored = any(sp.startswith(v.lower() + "/") or sp == v.lower() for v in vendored_keys)
        st.generated = generated_file(root / st.path)


def ext_summary(stats: list[FileStat]) -> list[dict]:
    acc: dict[str, dict[str, int]] = defaultdict(lambda: {"files": 0, "code": 0, "comment": 0, "blank": 0})
    for st in stats:
        a = acc[st.ext]
        a["files"] += 1
        a["code"] += st.code
        a["comment"] += st.comment
        a["blank"] += st.blank
    rows = []
    for ext, d in sorted(acc.items(), key=lambda kv: -(kv[1]["code"] + kv[1]["comment"] + kv[1]["blank"])):
        rows.append({"ext": ext, **d, "total": d["code"] + d["comment"] + d["blank"]})
    return rows


def top2_heatmap(stats: list[FileStat]) -> list[tuple[str, int]]:
    acc: dict[str, int] = defaultdict(int)
    for st in stats:
        p = Path(st.path)
        if len(p.parts) >= 2:
            key = f"{p.parts[0]}/{p.parts[1]}"
        else:
            key = p.parts[0]
        acc[key] += st.total
    return sorted(acc.items(), key=lambda kv: -kv[1])


def stats_hash(payload: dict) -> str:
    b = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return hashlib.sha256(b).hexdigest()[:16]


def write_by_file(path: Path, stats: list[FileStat]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["path", "ext", "language", "code", "comment", "blank", "total", "vendored", "generated"])
        for st in sorted(stats, key=lambda s: s.path):
            w.writerow([st.path, st.ext, st.language, st.code, st.comment, st.blank, st.total, int(st.vendored), int(st.generated)])


def build_markdown(root: Path, stats: list[FileStat], method: str) -> tuple[str, dict]:
    total = sum(s.total for s in stats)
    vendored = sum(s.total for s in stats if s.vendored)
    generated = sum(s.total for s in stats if s.generated)
    clean = total - vendored - generated

    vendored_dirs = vendored_candidates(root, stats)
    generated_files = sorted([s for s in stats if s.generated], key=lambda s: -s.total)[:30]
    exts = ext_summary(stats)
    heat = top2_heatmap(stats)[:30]
    header_total = sum(r["total"] for r in exts if r["ext"] in {".h", ".hh", ".hpp", ".hxx"})

    summary_obj = {
        "root": str(root),
        "count_files": len(stats),
        "total_lines": total,
        "vendored_lines": vendored,
        "generated_lines": generated,
        "estimated_handwritten_lines": clean,
        "method": method,
        "generated_files_top": [s.path for s in generated_files],
    }
    digest = stats_hash(summary_obj)

    lines = [
        "# WireBonder Corpus Recon (Scout Report)",
        "",
        f"- 时间(UTC): {utc_now()}",
        f"- 根目录: `{root}`",
        f"- 统计方式: `{method}`（cloc 不可用时自动 fallback）",
        f"- 文件数(仅目标扩展): **{len(stats)}**",
        f"- 总行数(code+comment+blank): **{total:,}**",
        f"- vendored 候选行数: **{vendored:,}** ({(vendored / total * 100 if total else 0):.1f}%)",
        f"- generated 候选行数: **{generated:,}** ({(generated / total * 100 if total else 0):.1f}%)",
        f"- 估算“真实手写逻辑”行数: **{clean:,}**",
        f"- recon 摘要哈希: `{digest}`",
        "",
        "## vendored/第三方候选目录（人工最终判定）",
        "",
        "| 目录 | 行数 | 占比 |",
        "|------|------:|-----:|",
    ]
    for d, n in list(vendored_dirs.items())[:30]:
        lines.append(f"| `{d}` | {n:,} | {(n / total * 100 if total else 0):.1f}% |")
    if not vendored_dirs:
        lines.append("| (none) | 0 | 0.0% |")

    lines += [
        "",
        "## generated 候选文件（Top 30）",
        "",
        "| 文件 | 行数 | 原因(启发式) |",
        "|------|-----:|---------------|",
    ]
    for s in generated_files:
        reason = ".rc 扩展或头部包含 generated/classwizard/do not edit"
        lines.append(f"| `{s.path}` | {s.total:,} | {reason} |")
    if not generated_files:
        lines.append("| (none) | 0 | - |")

    lines += [
        "",
        "## 扩展名分布",
        "",
        "| 扩展名 | 文件数 | 行数 | 占比 |",
        "|--------|-------:|-----:|-----:|",
    ]
    for r in exts:
        lines.append(f"| `{r['ext']}` | {r['files']} | {r['total']:,} | {(r['total']/total*100 if total else 0):.1f}% |")

    lines += [
        "",
        f"- 头文件行数占比(`.h/.hh/.hpp/.hxx`): **{(header_total/total*100 if total else 0):.1f}%**",
        "",
        "## 目录树前两层热力分布（Top 30）",
        "",
        "| 目录(前两层) | 行数 | 占比 |",
        "|--------------|-----:|-----:|",
    ]
    for d, n in heat:
        lines.append(f"| `{d}` | {n:,} | {(n/total*100 if total else 0):.1f}% |")

    lines += [
        "",
        "## 说明",
        "",
        "- 本报告只做语料构成侦察，不触发建索引/检索。",
        "- vendored/generated 均为候选启发式；最终剔除由人工确认。",
    ]
    return "\n".join(lines), {"digest": digest, **summary_obj}


def main() -> int:
    p = argparse.ArgumentParser(description="Corpus reconnaissance")
    p.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    p.add_argument("--out-md", type=Path, default=DEFAULT_NOTES)
    p.add_argument("--out-by-file", type=Path, default=DEFAULT_BY_FILE)
    p.add_argument("--out-summary", type=Path, default=DEFAULT_SUMMARY)
    p.add_argument(
        "--corpus-tag",
        default="",
        help="Optional tag suffix for output filenames (e.g. r12345).",
    )
    args = p.parse_args()

    if not args.root.is_dir():
        raise SystemExit(f"root not found: {args.root}")

    stats = parse_with_cloc(args.root)
    method = "cloc --by-file --csv"
    if stats is None:
        method = "builtin-counter (cloc unavailable)"
        stats = parse_builtin(args.root)

    mark_flags(args.root, stats)
    md, summary = build_markdown(args.root, stats, method)

    out_md = args.out_md
    out_by_file = args.out_by_file
    out_summary = args.out_summary
    if args.corpus_tag:
        tag = args.corpus_tag
        out_md = out_md.with_name(f"{out_md.stem}_{tag}{out_md.suffix}")
        out_by_file = out_by_file.with_name(f"{out_by_file.stem}_{tag}{out_by_file.suffix}")
        out_summary = out_summary.with_name(f"{out_summary.stem}_{tag}{out_summary.suffix}")

    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(md, encoding="utf-8")
    write_by_file(out_by_file, stats)
    out_summary.parent.mkdir(parents=True, exist_ok=True)
    out_summary.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Wrote {out_md}")
    print(f"Wrote {out_by_file}")
    print(f"Wrote {out_summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
