"""
Phase C repo probe: scan a C/C++ repository before indexing.

The probe is intentionally read-only. It reports scale, encoding, ctags
compatibility, risky files, and an indexing feasibility estimate.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from rich import box
from rich.console import Console
from rich.table import Table

LAB_ROOT = Path(__file__).parent.parent
SOURCE_EXTS = {".cpp", ".h", ".hpp", ".c"}
DEFAULT_SKIP_DIRS = {
    ".git", ".svn", ".hg", ".vs", ".vscode",
    "build", "cmake-build-debug", "cmake-build-release", "out", "dist",
    "node_modules", "__pycache__",
}

LARGE_FILE_LINES = 3000
TOP_LIMIT = 20
SCAN_LINES_PER_SEC = 800_000.0
CTAGS_LINES_PER_SEC = 33_000.0
CHUNKS_MB_PER_LINE = 14.0 / 800_617.0


def split_excludes(values: list[str]) -> set[str]:
    out: set[str] = set()
    for value in values:
        out.update(part.strip() for part in value.split(",") if part.strip())
    return out


def should_skip(path: Path, skip_dirs: set[str]) -> bool:
    return any(part in skip_dirs for part in path.parts)


def read_bytes(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError:
        return b""


def classify_encoding(data: bytes) -> tuple[str, bool]:
    if not data:
        return "empty", False
    if b"\x00" in data[:4096]:
        return "binary", True
    for label, encoding in (
        ("utf-8", "utf-8"),
        ("gb18030", "gb18030"),
        ("latin-1", "latin-1"),
    ):
        try:
            data.decode(encoding)
            return label, False
        except UnicodeDecodeError:
            continue
    return "unknown", True


def decode_preview(data: bytes, encoding: str) -> str:
    if encoding in {"binary", "unknown"}:
        return ""
    codec = "gb18030" if encoding == "gb18030" else encoding
    try:
        return data.decode(codec, errors="replace")
    except LookupError:
        return data.decode("utf-8", errors="replace")


def count_lines_text(text: str) -> int:
    if not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def top_dir(rel: Path) -> str:
    return rel.parts[0] if len(rel.parts) > 1 else "."


def sha256_short(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:16]


def is_generated(text: str) -> bool:
    lower = text[:20_000].lower()
    markers = (
        "generated", "do not edit", "auto-generated", "autogenerated",
        "automatically generated",
    )
    if any(marker in lower for marker in markers):
        return True
    lines = text.splitlines()[:300]
    if not lines:
        return False
    pragma_count = sum(1 for line in lines if line.lstrip().startswith("#pragma"))
    return pragma_count >= 10 and pragma_count / len(lines) >= 0.08


def scan_files(repo_root: Path, skip_dirs: set[str]) -> tuple[list[dict], dict[str, Any]]:
    records: list[dict] = []
    name_groups: dict[str, list[str]] = defaultdict(list)
    hash_groups: dict[str, list[str]] = defaultdict(list)

    for path in sorted(repo_root.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in SOURCE_EXTS:
            continue
        rel_path = path.relative_to(repo_root)
        if should_skip(rel_path, skip_dirs):
            continue

        data = read_bytes(path)
        encoding, binary_like = classify_encoding(data)
        text = decode_preview(data, encoding)
        lines = count_lines_text(text) if not binary_like else 0
        rel = str(rel_path).replace("\\", "/")
        digest = sha256_short(data)

        record = {
            "path": rel,
            "suffix": path.suffix.lower(),
            "size_bytes": path.stat().st_size,
            "lines": lines,
            "top_dir": top_dir(rel_path),
            "encoding": encoding,
            "binary_like": binary_like,
            "generated_like": is_generated(text) if text else False,
            "sha256": digest,
        }
        records.append(record)
        name_groups[path.name].append(rel)
        hash_groups[digest].append(rel)

    duplicate_names = {
        name: paths for name, paths in name_groups.items()
        if len(paths) > 1
    }
    duplicate_hashes = {
        digest: paths for digest, paths in hash_groups.items()
        if len(paths) > 1 and digest
    }
    return records, {
        "duplicate_names": duplicate_names,
        "duplicate_hashes": duplicate_hashes,
    }


def find_ctags() -> str | None:
    candidates: list[str] = []
    found = shutil.which("ctags")
    if found:
        candidates.append(found)
    winget_base = Path.home() / "AppData/Local/Microsoft/WinGet/Packages"
    candidates.extend(str(p) for p in winget_base.glob("UniversalCtags*/**/ctags.exe"))

    for candidate in candidates:
        try:
            result = subprocess.run(
                [candidate, "--version"], capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=5,
            )
        except (OSError, subprocess.TimeoutExpired):
            continue
        if result.returncode == 0:
            return candidate
    return None


def normalize_ctags_path(raw_path: str, repo_root: Path) -> str:
    path = Path(raw_path)
    try:
        return str(path.resolve().relative_to(repo_root)).replace("\\", "/")
    except (OSError, ValueError):
        return raw_path.replace("\\", "/")


def run_ctags(repo_root: Path, records: list[dict]) -> dict[str, Any]:
    ctags = find_ctags()
    empty = {
        "available": False,
        "exit_code": None,
        "symbol_counts": {},
        "symbols_by_file": {},
        "empty_or_failed_files": [r["path"] for r in records],
        "stderr": "ctags not found",
    }
    if not ctags or not records:
        return empty

    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as tmp:
        list_path = Path(tmp.name)
        for rec in records:
            tmp.write(str((repo_root / rec["path"]).resolve()) + "\n")

    cmd = [
        ctags,
        "--output-format=json",
        "--c++-kinds=+pfscetud",
        "--fields=+nKze",
        "--extras=-F",
        "-L", str(list_path),
        "-f", "-",
    ]
    try:
        result = subprocess.run(
            cmd, cwd=str(repo_root), capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        try:
            list_path.unlink()
        except OSError:
            pass
        empty["stderr"] = str(exc)
        return empty
    finally:
        try:
            list_path.unlink()
        except OSError:
            pass

    kind_counts: Counter[str] = Counter()
    by_file: dict[str, Counter[str]] = defaultdict(Counter)
    supported_kinds = {"class", "function", "macro", "namespace", "enum", "struct"}

    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        try:
            tag = json.loads(line)
        except json.JSONDecodeError:
            continue
        kind = str(tag.get("kind") or "")
        if kind not in supported_kinds:
            continue
        rel = normalize_ctags_path(str(tag.get("path") or ""), repo_root)
        kind_counts[kind] += 1
        by_file[rel][kind] += 1

    files_with_symbols = set(by_file)
    empty_or_failed = [
        rec["path"] for rec in records
        if rec["path"] not in files_with_symbols and not rec["binary_like"]
    ]
    return {
        "available": True,
        "exit_code": result.returncode,
        "symbol_counts": dict(kind_counts),
        "symbols_by_file": {path: dict(counts) for path, counts in by_file.items()},
        "empty_or_failed_files": empty_or_failed,
        "stderr": result.stderr[-4000:],
    }


def build_summary(records: list[dict], duplicates: dict[str, Any], ctags: dict[str, Any]) -> dict:
    by_ext = Counter(rec["suffix"] for rec in records)
    by_encoding = Counter(rec["encoding"] for rec in records)
    by_dir: dict[str, dict[str, Any]] = defaultdict(
        lambda: {"files": 0, "lines": 0, "symbols": Counter()}
    )

    symbols_by_file = ctags.get("symbols_by_file", {})
    for rec in records:
        d = by_dir[rec["top_dir"]]
        d["files"] += 1
        d["lines"] += rec["lines"]
        for kind, count in symbols_by_file.get(rec["path"], {}).items():
            d["symbols"][kind] += count

    large_files = [
        {"path": rec["path"], "lines": rec["lines"]}
        for rec in records if rec["lines"] > LARGE_FILE_LINES
    ]
    generated_files = [
        {"path": rec["path"], "lines": rec["lines"]}
        for rec in records if rec["generated_like"]
    ]
    binary_files = [
        {"path": rec["path"], "encoding": rec["encoding"], "size_bytes": rec["size_bytes"]}
        for rec in records if rec["binary_like"]
    ]
    encoding_anomalies = [
        {"path": rec["path"], "encoding": rec["encoding"]}
        for rec in records if rec["encoding"] not in {"utf-8", "empty"}
    ]
    total_lines = sum(rec["lines"] for rec in records)
    ctags_failed_count = len(ctags.get("empty_or_failed_files", []))
    ctags_fail_rate = ctags_failed_count / len(records) if records else 0.0

    risk_points = 0
    if len(large_files) > 5:
        risk_points += 2
    elif large_files:
        risk_points += 1
    if len(encoding_anomalies) > max(5, len(records) * 0.05):
        risk_points += 2
    elif encoding_anomalies:
        risk_points += 1
    if ctags_fail_rate > 0.15:
        risk_points += 2
    elif ctags_fail_rate > 0.05:
        risk_points += 1
    if binary_files:
        risk_points += 1

    risk_level = "高" if risk_points >= 4 else "中" if risk_points >= 2 else "低"
    recommendations: list[str] = []
    if large_files:
        recommendations.append("先确认超长文件是否为第三方或生成代码，必要时通过 --exclude 排除目录。")
    if encoding_anomalies:
        recommendations.append("迁移前确认 GBK/GB18030 文件读取策略，避免 line number 与源码显示不一致。")
    if ctags_fail_rate > 0.05:
        recommendations.append("抽查 ctags 空结果文件，必要时补充宏/消息映射专用规则。")
    if generated_files:
        recommendations.append("generated-like 文件建议默认不作为业务问答重点。")
    if not recommendations:
        recommendations.append("风险较低，可进入小范围索引构建与 10 个真实问题验证。")

    return {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "repo_root": "",
        "file_stats": {
            "file_count": len(records),
            "total_lines": total_lines,
            "avg_lines_per_file": round(total_lines / len(records), 1) if records else 0,
            "by_extension": dict(by_ext),
            "largest_files": sorted(
                [{"path": r["path"], "lines": r["lines"], "size_bytes": r["size_bytes"]}
                 for r in records],
                key=lambda item: item["lines"],
                reverse=True,
            )[:TOP_LIMIT],
        },
        "encoding": {
            "counts": dict(by_encoding),
            "anomalies": encoding_anomalies[:TOP_LIMIT],
        },
        "ctags": ctags,
        "risks": {
            "large_files": sorted(large_files, key=lambda item: -item["lines"])[:TOP_LIMIT],
            "generated_files": generated_files[:TOP_LIMIT],
            "binary_or_garbled_files": binary_files[:TOP_LIMIT],
            "duplicate_names": dict(list(duplicates["duplicate_names"].items())[:TOP_LIMIT]),
            "duplicate_hashes": dict(list(duplicates["duplicate_hashes"].items())[:TOP_LIMIT]),
        },
        "directory_map": {
            name: {
                "files": value["files"],
                "lines": value["lines"],
                "symbols": dict(value["symbols"]),
            }
            for name, value in sorted(by_dir.items(), key=lambda item: -item[1]["lines"])
        },
        "feasibility": {
            "estimated_scan_seconds": round(total_lines / SCAN_LINES_PER_SEC, 2),
            "estimated_ctags_seconds": round(total_lines / CTAGS_LINES_PER_SEC, 2),
            "estimated_chunks_mb": round(total_lines * CHUNKS_MB_PER_LINE, 1),
            "ctags_fail_rate": round(ctags_fail_rate, 4),
            "risk_level": risk_level,
            "recommendations": recommendations,
        },
    }


def render_terminal(report: dict) -> None:
    console = Console()
    stats = report["file_stats"]
    feasibility = report["feasibility"]

    console.rule("[bold]kb probe[/]")
    summary = Table(box=box.SIMPLE_HEAVY, show_header=False)
    summary.add_column("Field", style="bold cyan")
    summary.add_column("Value")
    summary.add_row("files", str(stats["file_count"]))
    summary.add_row("lines", f"{stats['total_lines']:,}")
    summary.add_row("avg lines/file", str(stats["avg_lines_per_file"]))
    summary.add_row("risk", feasibility["risk_level"])
    summary.add_row("ctags fail rate", f"{feasibility['ctags_fail_rate']:.1%}")
    console.print(summary)

    dir_table = Table(title="Directory Map", box=box.SIMPLE)
    dir_table.add_column("dir")
    dir_table.add_column("files", justify="right")
    dir_table.add_column("lines", justify="right")
    dir_table.add_column("symbols")
    for name, row in list(report["directory_map"].items())[:12]:
        symbols = ", ".join(f"{k}:{v}" for k, v in row["symbols"].items()) or "-"
        dir_table.add_row(name, str(row["files"]), f"{row['lines']:,}", symbols)
    console.print(dir_table)

    if stats["largest_files"]:
        large = Table(title="Largest Files", box=box.SIMPLE)
        large.add_column("file")
        large.add_column("lines", justify="right")
        for item in stats["largest_files"][:10]:
            large.add_row(item["path"], f"{item['lines']:,}")
        console.print(large)


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(out)


def render_markdown(report: dict) -> str:
    stats = report["file_stats"]
    feasibility = report["feasibility"]
    lines = [
        "# Repo Probe Report",
        "",
        f"- Created: `{report['created_at']}`",
        f"- Files: **{stats['file_count']}**",
        f"- Lines: **{stats['total_lines']:,}**",
        f"- Risk level: **{feasibility['risk_level']}**",
        "",
        "## File Statistics",
        "",
        md_table(
            ["Extension", "Files"],
            [[ext, count] for ext, count in sorted(stats["by_extension"].items())],
        ),
        "",
        "### Largest Files",
        "",
        md_table(
            ["File", "Lines", "Size bytes"],
            [[i["path"], f"{i['lines']:,}", i["size_bytes"]] for i in stats["largest_files"]],
        ),
        "",
        "## Encoding",
        "",
        md_table(
            ["Encoding", "Files"],
            [[enc, count] for enc, count in sorted(report["encoding"]["counts"].items())],
        ),
        "",
        "### Encoding Anomalies",
        "",
        md_table(
            ["File", "Encoding"],
            [[i["path"], i["encoding"]] for i in report["encoding"]["anomalies"]],
        ) if report["encoding"]["anomalies"] else "No encoding anomalies detected.",
        "",
        "## Ctags Structure",
        "",
        f"- Available: `{report['ctags']['available']}`",
        f"- Exit code: `{report['ctags']['exit_code']}`",
        f"- Empty or failed files: **{len(report['ctags']['empty_or_failed_files'])}**",
        "",
        md_table(
            ["Kind", "Count"],
            [[kind, count] for kind, count in sorted(report["ctags"]["symbol_counts"].items())],
        ),
        "",
        "## Risk Files",
        "",
        "### Large Files",
        "",
        md_table(
            ["File", "Lines"],
            [[i["path"], f"{i['lines']:,}"] for i in report["risks"]["large_files"]],
        ) if report["risks"]["large_files"] else "No files above threshold.",
        "",
        "### Generated-Like Files",
        "",
        md_table(
            ["File", "Lines"],
            [[i["path"], f"{i['lines']:,}"] for i in report["risks"]["generated_files"]],
        ) if report["risks"]["generated_files"] else "No generated-like files detected.",
        "",
        "### Binary Or Garbled Files",
        "",
        md_table(
            ["File", "Encoding", "Size bytes"],
            [[i["path"], i["encoding"], i["size_bytes"]] for i in report["risks"]["binary_or_garbled_files"]],
        ) if report["risks"]["binary_or_garbled_files"] else "No binary or garbled source files detected.",
        "",
        "## Directory Code Map",
        "",
        md_table(
            ["Directory", "Files", "Lines", "Symbols"],
            [
                [
                    name,
                    row["files"],
                    f"{row['lines']:,}",
                    ", ".join(f"{k}:{v}" for k, v in row["symbols"].items()) or "-",
                ]
                for name, row in report["directory_map"].items()
            ],
        ),
        "",
        "## Index Feasibility",
        "",
        f"- Estimated scan time: **{feasibility['estimated_scan_seconds']} s**",
        f"- Estimated ctags time: **{feasibility['estimated_ctags_seconds']} s**",
        f"- Estimated chunks size: **{feasibility['estimated_chunks_mb']} MB**",
        f"- Ctags fail rate: **{feasibility['ctags_fail_rate']:.1%}**",
        f"- Risk level: **{feasibility['risk_level']}**",
        "",
        "### Recommendations",
        "",
    ]
    lines.extend(f"- {item}" for item in feasibility["recommendations"])
    lines.append("")
    return "\n".join(lines)


def probe(repo_root: Path, excludes: list[str] | None = None) -> dict:
    repo_root = repo_root.resolve()
    if not repo_root.is_dir():
        raise SystemExit(f"repo_root 不存在: {repo_root}")
    skip_dirs = DEFAULT_SKIP_DIRS | split_excludes(excludes or [])
    records, duplicates = scan_files(repo_root, skip_dirs)
    ctags = run_ctags(repo_root, records)
    report = build_summary(records, duplicates, ctags)
    report["repo_root"] = str(repo_root)
    return report


def write_outputs(report: dict, out: Path | None, json_path: Path | None) -> None:
    if out is not None:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render_markdown(report), encoding="utf-8")
    if json_path is not None:
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Probe a C/C++ repository before indexing")
    parser.add_argument("--repo-root", required=True, help="源码仓库根目录")
    parser.add_argument("--out", default=None, help="Markdown report 输出路径")
    parser.add_argument("--json", action="store_true", help="输出 JSON 到 stdout")
    parser.add_argument("--json-out", default=None, help="JSON report 输出路径")
    parser.add_argument("--exclude", action="append", default=[], help="额外跳过的目录名")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    report = probe(Path(args.repo_root), args.exclude)
    write_outputs(
        report,
        Path(args.out).resolve() if args.out else None,
        Path(args.json_out).resolve() if args.json_out else None,
    )
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        render_terminal(report)
        if args.out:
            Console().print(f"[green]report ->[/] {Path(args.out).resolve()}")


if __name__ == "__main__":
    main()
